name: ci

on:
  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Shorten SHA
        shell: bash
        run: |
          echo "COMMIT_ID=$(echo $GITHUB_SHA::6}" >> "$GITHUB_ENV"
      
      
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          # context: .
          push: true
          tags: sukhsaggu2020/python-app:${{ env.COMMIT_ID }}